# Generated by Django 4.2.1 on 2023-05-30 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookworms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBook', models.ForeignKey(db_column='idBook', on_delete=django.db.models.deletion.CASCADE, to='bookworms.book')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RecommendationList',
            },
        ),
        migrations.CreateModel(
            name='HasBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idBadge', models.ForeignKey(db_column='idBadge', on_delete=django.db.models.deletion.CASCADE, to='bookworms.badge')),
                ('idUser', models.ForeignKey(db_column='idUser', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('idBadge', 'idUser')},
            },
        ),
    ]
