# Generated by Django 4.2.1 on 2023-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readlist',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='rating_fin',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
