# Generated by Django 4.2.1 on 2023-06-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookworms', '0002_remove_readlist_rating_book_rating_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating_fin',
            field=models.FloatField(default=0, null=True),
        ),
    ]
