# Generated by Django 4.2.1 on 2023-05-30 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookworms', '0002_recommendationlist_hasbadge'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hasbadge',
            table='HasBadge',
        ),
    ]
